openapi: 3.0.0
info: 
  title: Songs API
  version: 0.0.1

paths:
  /:
    get:
      description: Returns a greeting message from Songs API
      operationId: greetingMessage
      responses:
        '200':
          description: OK
          content:
            application/json:
              example:
                {
                  "message": "Hello from Songs API"
                }

components:
  schemas:


